#!/bin/sh

set -u # Treat unset variables as an error.

exec socat TCP-LISTEN:${CHROMIUM_REMOTE_DEBUGGING_PORT:-9222},fork TCP:127.0.0.1:$((${CHROMIUM_REMOTE_DEBUGGING_PORT:-9222} + 1))

# vim:ft=sh:ts=4:sw=4:et:sts=4
